📝 Generating SQL INSERT statements...

-- SQL INSERT statements for events table
-- Copy and paste this into your Supabase SQL Editor

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Beach Cleanup at Dockweiler',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🌿 Environment',
  '2025-08-22',
  '10:00',
  '14:00',
  '100 Main St, Los Angeles, CA 90000',
  34.05,
  -118.25,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  true,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Tree Planting in Griffith Park',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🌿 Environment',
  '2025-08-09',
  '10:00',
  '14:00',
  '101 Main St, Los Angeles, CA 90001',
  34.059999999999995,
  -118.26,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  true,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Urban Gardening Workshop',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🌿 Environment',
  '2025-07-05',
  '10:00',
  '14:00',
  '102 Main St, Los Angeles, CA 90002',
  34.07,
  -118.27,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  true,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Park Beautification in Echo Park',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🌿 Environment',
  '2025-07-07',
  '10:00',
  '14:00',
  '103 Main St, Los Angeles, CA 90003',
  34.08,
  -118.28,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  true,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Riverbed Restoration',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🌿 Environment',
  '2025-08-16',
  '10:00',
  '14:00',
  '104 Main St, Los Angeles, CA 90004',
  34.089999999999996,
  -118.29,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  true,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Sustainability Fair Volunteer',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🌿 Environment',
  '2025-07-16',
  '10:00',
  '14:00',
  '105 Main St, Los Angeles, CA 90005',
  34.099999999999994,
  -118.3,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  true,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Recycling Awareness Booth',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🌿 Environment',
  '2025-07-19',
  '10:00',
  '14:00',
  '106 Main St, Los Angeles, CA 90006',
  34.11,
  -118.31,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  true,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Compost and Green Waste Day',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🌿 Environment',
  '2025-07-09',
  '10:00',
  '14:00',
  '107 Main St, Los Angeles, CA 90007',
  34.12,
  -118.32,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  true,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Eco-Art Install Support',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🌿 Environment',
  '2025-08-11',
  '10:00',
  '14:00',
  '108 Main St, Los Angeles, CA 90008',
  34.129999999999995,
  -118.33,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  true,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Bike Path Trash Sweep',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🌿 Environment',
  '2025-08-30',
  '10:00',
  '14:00',
  '109 Main St, Los Angeles, CA 90009',
  34.14,
  -118.34,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  true,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Neighborhood Mural Painting',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🏘️ Community',
  '2025-08-12',
  '10:00',
  '14:00',
  '110 Main St, Los Angeles, CA 90010',
  34.15,
  -118.35,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Civic Engagement Voter Drive',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🏘️ Community',
  '2025-07-24',
  '10:00',
  '14:00',
  '111 Main St, Los Angeles, CA 90011',
  34.16,
  -118.36,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'LGBTQ+ Pride Event Support',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🏘️ Community',
  '2025-08-28',
  '10:00',
  '14:00',
  '112 Main St, Los Angeles, CA 90012',
  34.169999999999995,
  -118.37,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Refugee Welcome Orientation',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🏘️ Community',
  '2025-08-20',
  '10:00',
  '14:00',
  '113 Main St, Los Angeles, CA 90013',
  34.18,
  -118.38,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Community Potluck Organizer',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🏘️ Community',
  '2025-07-12',
  '10:00',
  '14:00',
  '114 Main St, Los Angeles, CA 90014',
  34.19,
  -118.39,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'LA Food Bank Volunteer Day',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🤝 Care & Relief',
  '2025-07-06',
  '10:00',
  '14:00',
  '120 Main St, Los Angeles, CA 90020',
  34.25,
  -118.45,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Union Rescue Mission Volunteer Day',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🤝 Care & Relief',
  '2025-07-14',
  '10:00',
  '14:00',
  '121 Main St, Los Angeles, CA 90021',
  34.26,
  -118.46,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Midnight Mission Volunteer Day',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🤝 Care & Relief',
  '2025-07-29',
  '10:00',
  '14:00',
  '122 Main St, Los Angeles, CA 90022',
  34.269999999999996,
  -118.47,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'PATH Volunteer Day',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🤝 Care & Relief',
  '2025-07-28',
  '10:00',
  '14:00',
  '123 Main St, Los Angeles, CA 90023',
  34.279999999999994,
  -118.48,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'LA Mission Volunteer Day',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🤝 Care & Relief',
  '2025-07-31',
  '10:00',
  '14:00',
  '124 Main St, Los Angeles, CA 90024',
  34.29,
  -118.49,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Central Library Tutoring Day',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '📚 Youth & Education',
  '2025-08-02',
  '10:00',
  '14:00',
  '130 Main St, Los Angeles, CA 90030',
  34.349999999999994,
  -118.55,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  '826LA Writing Workshop',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '📚 Youth & Education',
  '2025-07-08',
  '10:00',
  '14:00',
  '131 Main St, Los Angeles, CA 90031',
  34.36,
  -118.56,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Boys & Girls Club Venice Day',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '📚 Youth & Education',
  '2025-08-19',
  '10:00',
  '14:00',
  '132 Main St, Los Angeles, CA 90032',
  34.37,
  -118.57,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Reading to Kids Volunteer Day',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '📚 Youth & Education',
  '2025-08-07',
  '10:00',
  '14:00',
  '133 Main St, Los Angeles, CA 90033',
  34.379999999999995,
  -118.58,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'PUENTE Learning Center Tutor Day',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '📚 Youth & Education',
  '2025-08-25',
  '10:00',
  '14:00',
  '134 Main St, Los Angeles, CA 90034',
  34.39,
  -118.59,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'LA Animal Services Dog Day',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '❤️ Health & Animals',
  '2025-08-23',
  '10:00',
  '14:00',
  '140 Main St, Los Angeles, CA 90040',
  34.449999999999996,
  -118.65,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'NKLA Pet Adoption Support',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '❤️ Health & Animals',
  '2025-08-01',
  '10:00',
  '14:00',
  '141 Main St, Los Angeles, CA 90041',
  34.459999999999994,
  -118.66,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'PAWS/LA Outreach Event',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '❤️ Health & Animals',
  '2025-07-02',
  '10:00',
  '14:00',
  '142 Main St, Los Angeles, CA 90042',
  34.47,
  -118.67,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Didi Hirsch Mental Health Support',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '❤️ Health & Animals',
  '2025-07-21',
  '10:00',
  '14:00',
  '143 Main St, Los Angeles, CA 90043',
  34.48,
  -118.68,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Venice Family Clinic Drive',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '❤️ Health & Animals',
  '2025-08-18',
  '10:00',
  '14:00',
  '144 Main St, Los Angeles, CA 90044',
  34.489999999999995,
  -118.69,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'First AME Church Community Day',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🕊️ Faith-Based',
  '2025-07-26',
  '10:00',
  '14:00',
  '150 Main St, Los Angeles, CA 90050',
  34.55,
  -118.75,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Wilshire Blvd Temple Youth Drive',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🕊️ Faith-Based',
  '2025-08-24',
  '10:00',
  '14:00',
  '151 Main St, Los Angeles, CA 90051',
  34.559999999999995,
  -118.76,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Islamic Center of SoCal Support',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🕊️ Faith-Based',
  '2025-07-22',
  '10:00',
  '14:00',
  '152 Main St, Los Angeles, CA 90052',
  34.57,
  -118.77,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'St. Sophia Cathedral Volunteer Day',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🕊️ Faith-Based',
  '2025-08-29',
  '10:00',
  '14:00',
  '153 Main St, Los Angeles, CA 90053',
  34.58,
  -118.78,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time_start,
  time_end,
  location_address,
  location_latitude,
  location_longitude,
  external_url,
  organization_name,
  is_virtual,
  is_featured,
  status
) VALUES (
  'Immanuel Presbyterian Youth Camp',
  'A great opportunity to serve in the environment space and make a meaningful impact.',
  '🕊️ Faith-Based',
  '2025-07-04',
  '10:00',
  '14:00',
  '154 Main St, Los Angeles, CA 90054',
  34.589999999999996,
  -118.79,
  'https://www.example.com/event',
  'Voluntr Community',
  false,
  false,
  'active'
);

-- Migration completed!
-- Total events: 35
